name: Daily Data Fetcher

on:
  schedule:
    # Runs at 01:00 UTC, which is 9:00 AM in China Standard Time (UTC+8)
    - cron: '0 1 * * *'  
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Fetch opening projects
      run: python fetch_opening_projects.py

    - name: Fetch purchase bulletins
      run: python fetch_purchase_bulletins.py
    
    - name: Run project classifier
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
      run: python classify_projects.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add opening_projects.json purchase_bulletins.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update opening & purchase bulletins data [skip ci]" && git push)
        
    - name: Run DingTalk info push
      env:
        DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
      run: python ding_push_opening_projects.py
    
    # - name: Run Bark info push
    #   env:
    #     BARK_KEY: ${{ secrets.BARK_KEY }}
    #   run: python bark_push_opening_projects.py