name: Daily Data Fetcher

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 18:00 UTC+8 (10:00 UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run data fetcher
      run: python fetch_bidding.py
    
    - name: Run project classifier
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
      run: python classify_projects.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add date_prj.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update bidding data [skip ci]" && git push)
        
    # - name: Run info push
    #   env:
    #     BARK_KEY: ${{ secrets.BARK_KEY }}
    #   run: python nbygcg_info_bark_push.py